
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class frmMain extends javax.swing.JFrame {

    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        perempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblalamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        lblemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblkelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblnis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblnama = new javax.swing.JTextField();
        tmpt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lahir = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 200, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 360, 40);

        labeltanggal.setText("Tanggal");
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(540, 10, 60, 14);

        labeljam.setText("Jam");
        jPanel1.add(labeljam);
        labeljam.setBounds(540, 30, 60, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 60);

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));
        jPanel3.setLayout(null);

        tblData.setBackground(new java.awt.Color(102, 255, 51));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "TempatLahir", "TanggalLahir", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 470, 400);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, 140, 490, 420);

        jPanel4.setBackground(new java.awt.Color(102, 255, 51));
        jPanel4.setLayout(null);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel4.add(save);
        save.setBounds(10, 20, 70, 23);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel4.add(delete);
        delete.setBounds(90, 20, 70, 23);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel4.add(clear);
        clear.setBounds(170, 20, 70, 23);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel4.add(refresh);
        refresh.setBounds(250, 20, 71, 23);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel4.add(edit);
        edit.setBounds(330, 20, 70, 23);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel4.add(print);
        print.setBounds(410, 20, 73, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(260, 70, 490, 60);

        jPanel5.setBackground(new java.awt.Color(102, 255, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Isian Data Siswa"));
        jPanel5.setLayout(null);

        perempuan.setBackground(new java.awt.Color(102, 255, 51));
        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel5.add(perempuan);
        perempuan.setBounds(80, 250, 110, 30);

        lblalamat.setColumns(20);
        lblalamat.setRows(5);
        jScrollPane1.setViewportView(lblalamat);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 420, 220, 70);

        jLabel9.setText("ALAMAT");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(10, 400, 100, 20);

        lblemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblemailActionPerformed(evt);
            }
        });
        jPanel5.add(lblemail);
        lblemail.setBounds(10, 370, 140, 30);

        jLabel8.setText("EMAIL");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(10, 340, 100, 20);
        jPanel5.add(lblkelas);
        lblkelas.setBounds(10, 300, 140, 30);

        jLabel7.setText("KELAS");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 280, 100, 20);

        laki.setBackground(new java.awt.Color(102, 255, 51));
        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel5.add(laki);
        laki.setBounds(10, 250, 100, 30);

        jLabel6.setText("JENIS KELAMIN");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 230, 100, 20);

        jLabel4.setText("NIS");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 30, 80, 20);
        jPanel5.add(lblnis);
        lblnis.setBounds(10, 50, 140, 30);

        jLabel5.setText("NAMA");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 80, 90, 20);
        jPanel5.add(lblnama);
        lblnama.setBounds(10, 100, 140, 30);

        tmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmptActionPerformed(evt);
            }
        });
        jPanel5.add(tmpt);
        tmpt.setBounds(10, 150, 140, 30);

        jLabel10.setText("TANGGAL LAHIR");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 180, 90, 20);
        jPanel5.add(lahir);
        lahir.setBounds(10, 200, 140, 30);

        jLabel11.setText("TEMPAT LAHIR");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 130, 90, 20);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 70, 240, 500);

        setBounds(0, 0, 769, 604);
    }// </editor-fold>//GEN-END:initComponents

    private void lblemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblemailActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
          SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
          String tanggal = dateFormat.format(lahir.getDate());
           String JK= "";
               if(laki.isSelected()){
               }else{
                   JK="L";
               }
               if(perempuan.isSelected())
                   JK="P";
        if(lblnis.getText().equals("") ||  
                lblnama.getText().equals("") ||
                tanggal.equals("")||
                JK.equals("")||
                lblkelas.getText().equals("")||
                lblemail.getText().equals("")||
                tmpt.getText().equals("")||
                lblalamat.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", 
               JOptionPane.WARNING_MESSAGE);
           }else{
              
               String SQL="INSERT INTO t_siswa VALUES"
                       + "('"+lblnis.getText()+"',"
                       + "'"+lblnama.getText()+"','"+tanggal+"','"+JK+"','"
                       +"','"+lblkelas.getText()+"','"+lblemail.getText()
                       +"',"+tmpt.getText()+"',"
                       +"','"+lblalamat.getText()+"')";
                               int status = KoneksiDB.execute(SQL);
                               if(status== 1){
                                   JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                                   selectData();
                               }else{
                                   JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
                               }
           }
// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        lblnama.setText("");
        lblnis.setText("");
        lblkelas.setText("");
        buttonGroup1.clearSelection();
        lblemail.setText("");
        lblalamat.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
// TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if("".equals(lblnis.getText()) || "".equals(lblalamat.getText()) ||
                "".equals(lblkelas.getText()) || "".equals(lblnama.getText()) ||
                "".equals(lblemail.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String JK = "";
            if(laki.isSelected()){
                JK="L";
            }else{
                JK="P";
            }
            String SQL = "UPDATE t_siswa SET"
                    +"WHERE NamaSiswa='"+lblnama.getText()+"',"
                    +"WHERE JenisKelamin='"+JK+"',"
                    +"WHERE Kelas='"+lblkelas.getText()+"',"
                    +"WHERE Email='"+lblemail.getText()+"'"
                    +"WHERE Alamat='"+lblalamat.getText()+"'"
                    +"WHERE NIS='"+lblnis.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 0){
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            lblnis.setText(tblData.getValueAt(baris, 0).toString());
            lblnama.setText(tblData.getValueAt(baris, 1).toString());
            if("Laki-Laki".equals(tblData.getValueAt(baris, 2).toString())){
                laki.setSelected(true);
            }else{
                perempuan.setSelected(true);
            }
            lblkelas.setText(tblData.getValueAt(baris, 3).toString());
            lblemail.setText(tblData.getValueAt(baris, 4).toString());
            lblalamat.setText(tblData.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void tmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmptActionPerformed

    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal.setText (kal.format(skrg));
    }
    
    public void SetJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <=9){
                    nol_jam = "0";
                }
                if (nilai_menit<=9){
                    nol_menit = "0";
                }
                if (nilai_detik <=9){
                nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                labeljam.setText("Jam "+jam+":"+menit+":"+detik);
            }
           
        };
        new Timer(100, taskPerformer).start();
    }
    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK TELKOM Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}         ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer,true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private com.toedter.calendar.JDateChooser lahir;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextArea lblalamat;
    private javax.swing.JTextField lblemail;
    private javax.swing.JTextField lblkelas;
    private javax.swing.JTextField lblnama;
    private javax.swing.JTextField lblnis;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField tmpt;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[]={"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM t_siswa";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String NIS = rs.getString(1);
                        String NamaSiswa =rs.getString(2);
                        String JenisKelamin ="";
                        if("L".equals(rs.getString(3))){
                            JenisKelamin = "Laki-Laki";
                        }else{
                            JenisKelamin = "Perempuan";
                        }
                        String Kelas = rs.getString(4);
                        String Email = rs.getString(5);
                        String Alamat = rs.getString(6);
                        String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                        dtm.addRow(data);
                    }
                }catch(SQLException ex){
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null, ex);
                }
                tblData.setModel(dtm);
//To change body of generated methods, choose Tools | Templates.
    }
}
